
import { useState, useEffect } from 'react';

export interface Element {
  image: string;
  name: string;
  symbol: string;
  atomicNumber: number;
  atomicMass: number;
  category: string;
  period: number;
  group: number;
}

const elementData: Element[] = [
  {
    image: '../public/gold.jpg',
    name: 'Hydrogen',
    symbol: 'H',
    atomicNumber: 1,
    atomicMass: 1.008,
    category: 'Nonmetal',
    period: 1,
    group: 1,
  },
  {
    image: '/',
    name: 'Helium',
    symbol: 'He',
    atomicNumber: 2,
    atomicMass: 4.003,
    category: 'Noble Gas',
    period: 1,
    group: 18,
  },
  {
    image: '/',
    name: 'Lithium',
    symbol: 'Li',
    atomicNumber: 3,
    atomicMass: 6.941,
    category: 'Alkali Metal',
    period: 2,
    group: 1,
  },
  {
    image: '/',
    name: 'Beryllium',
    symbol: 'Be',
    atomicNumber: 4,
    atomicMass: 9.012,
    category: 'Alkaline Earth Metal',
    period: 2,
    group: 2,
  },
  {
    image: '/',
    name: 'Boron',
    symbol: 'B',
    atomicNumber: 5,
    atomicMass: 10.811,
    category: 'Metalloid',
    period: 2,
    group: 13,
  },
  {
    image: '/',
    name: 'Carbon',
    symbol: 'C',
    atomicNumber: 6,
    atomicMass: 12.011,
    category: 'Nonmetal',
    period: 2,
    group: 14,
  },
  {
    image: '/',
    name: 'Nitrogen',
    symbol: 'N',
    atomicNumber: 7,
    atomicMass: 14.007,
    category: 'Nonmetal',
    period: 2,
    group: 15,
  },
  {
    image: '/',
    name: 'Oxygen',
    symbol: 'O',
    atomicNumber: 8,
    atomicMass: 15.999,
    category: 'Nonmetal',
    period: 2,
    group: 16,
  },
  {
    image: '/',
    name: 'Fluorine',
    symbol: 'F',
    atomicNumber: 9,
    atomicMass: 18.998,
    category: 'Halogen',
    period: 2,
    group: 17,
  },
  {
    image: '/',
    name: 'Neon',
    symbol: 'Ne',
    atomicNumber: 10,
    atomicMass: 20.18,
    category: 'Noble Gas',
    period: 2,
    group: 18,
  },
  {
    image: '/',
    name: 'Sodium',
    symbol: 'Na',
    atomicNumber: 11,
    atomicMass: 22.99,
    category: 'Alkali Metal',
    period: 3,
    group: 1,
  },
  {
    image: '/',
    name: 'Magnesium',
    symbol: 'Mg',
    atomicNumber: 12,
    atomicMass: 24.305,
    category: 'Alkaline Earth Metal',
    period: 3,
    group: 2,
  },
  {
    image: '/',
    name: 'Aluminum',
    symbol: 'Al',
    atomicNumber: 13,
    atomicMass: 26.982,
    category: 'Post-Transition Metal',
    period: 3,
    group: 13,
  },
  {
    image: '/',
    name: 'Silicon',
    symbol: 'Si',
    atomicNumber: 14,
    atomicMass: 28.086,
    category: 'Metalloid',
    period: 3,
    group: 14,
  },
  {
    image: '/',
    name: 'Phosphorus',
    symbol: 'P',
    atomicNumber: 15,
    atomicMass: 30.974,
    category: 'Nonmetal',
    period: 3,
    group: 15,
  },
  {
    image: '/',
    name: 'Sulfur',
    symbol: 'S',
    atomicNumber: 16,
    atomicMass: 32.065,
    category: 'Nonmetal',
    period: 3,
    group: 16,
  },
  {
    image: '/',
    name: 'Chlorine',
    symbol: 'Cl',
    atomicNumber: 17,
    atomicMass: 35.453,
    category: 'Halogen',
    period: 3,
    group: 17,
  },
  {
    image: '/',
    name: 'Argon',
    symbol: 'Ar',
    atomicNumber: 18,
    atomicMass: 39.948,
    category: 'Noble Gas',
    period: 3,
    group: 18,
  },
  {
    image: '/',
    name: 'Potassium',
    symbol: 'K',
    atomicNumber: 19,
    atomicMass: 39.098,
    category: 'Alkali Metal',
    period: 4,
    group: 1,
  },
  {
    image: '/',
    name: 'Calcium',
    symbol: 'Ca',
    atomicNumber: 20,
    atomicMass: 40.078,
    category: 'Alkaline Earth Metal',
    period: 4,
    group: 2,
  },
  {
    image: '/',
    name: 'Scandium',
    symbol: 'Sc',
    atomicNumber: 21,
    atomicMass: 44.956,
    category: 'Transition Metal',
    period: 4,
    group: 3,
  },
  {
    image: '/',
    name: 'Titanium',
    symbol: 'Ti',
    atomicNumber: 22,
    atomicMass: 47.867,
    category: 'Transition Metal',
    period: 4,
    group: 4,
  },
  {
    image: '/',
    name: 'Vanadium',
    symbol: 'V',
    atomicNumber: 23,
    atomicMass: 50.942,
    category: 'Transition Metal',
    period: 4,
    group: 5,
  },
  {
    image: '/',
    name: 'Chromium',
    symbol: 'Cr',
    atomicNumber: 24,
    atomicMass: 51.996,
    category: 'Transition Metal',
    period: 4,
    group: 6,
  },
  {
    image: '/',
    name: 'Manganese',
    symbol: 'Mn',
    atomicNumber: 25,
    atomicMass: 54.938,
    category: 'Transition Metal',
    period: 4,
    group: 7,
  },
  {
    image: '/',
    name: 'Iron',
    symbol: 'Fe',
    atomicNumber: 26,
    atomicMass: 55.845,
    category: 'Transition Metal',
    period: 4,
    group: 8,
  },
  {
    image: '/',
    name: 'Cobalt',
    symbol: 'Co',
    atomicNumber: 27,
    atomicMass: 58.933,
    category: 'Transition Metal',
    period: 4,
    group: 9,
  },
  {
    image: '/',
    name: 'Nickel',
    symbol: 'Ni',
    atomicNumber: 28,
    atomicMass: 58.693,
    category: 'Transition Metal',
    period: 4,
    group: 10,
  },
  {
    image: '/',
    name: 'Copper',
    symbol: 'Cu',
    atomicNumber: 29,
    atomicMass: 63.546,
    category: 'Transition Metal',
    period: 4,
    group: 11,
  },
  {
    image: '/',
    name: 'Zinc',
    symbol: 'Zn',
    atomicNumber: 30,
    atomicMass: 65.38,
    category: 'Transition Metal',
    period: 4,
    group: 12,
  },
  {
    image: '/',
    name: 'Gallium',
    symbol: 'Ga',
    atomicNumber: 31,
    atomicMass: 69.723,
    category: 'Post-Transition Metal',
    period: 4,
    group: 13,
  },
  {
    image: '/',
    name: 'Germanium',
    symbol: 'Ge',
    atomicNumber: 32,
    atomicMass: 72.63,
    category: 'Metalloid',
    period: 4,
    group: 14,
  },
  {
    image: '/',
    name: 'Arsenic',
    symbol: 'As',
    atomicNumber: 33,
    atomicMass: 74.922,
    category: 'Metalloid',
    period: 4,
    group: 15,
  },
  {
    image: '/',
    name: 'Selenium',
    symbol: 'Se',
    atomicNumber: 34,
    atomicMass: 78.971,
    category: 'Nonmetal',
    period: 4,
    group: 16,
  },
  {
    image: '/',
    name: 'Bromine',
    symbol: 'Br',
    atomicNumber: 35,
    atomicMass: 79.904,
    category: 'Halogen',
    period: 4,
    group: 17,
  },
  {
    image: '/',
    name: 'Krypton',
    symbol: 'Kr',
    atomicNumber: 36,
    atomicMass: 83.798,
    category: 'Noble Gas',
    period: 4,
    group: 18,
  },
  {
    image: '/',
    name: 'Rubidium',
    symbol: 'Rb',
    atomicNumber: 37,
    atomicMass: 85.468,
    category: 'Alkali Metal',
    period: 5,
    group: 1,
  },
  {
    image: '/',
    name: 'Strontium',
    symbol: 'Sr',
    atomicNumber: 38,
    atomicMass: 87.62,
    category: 'Alkaline Earth Metal',
    period: 5,
    group: 2,
  },
  {
    image: '/',
    name: 'Yttrium',
    symbol: 'Y',
    atomicNumber: 39,
    atomicMass: 88.906,
    category: 'Transition Metal',
    period: 5,
    group: 3,
  },
  {
    image: '/',
    name: 'Zirconium',
    symbol: 'Zr',
    atomicNumber: 40,
    atomicMass: 91.224,
    category: 'Transition Metal',
    period: 5,
    group: 4,
  },
  {
    image: '/',
    name: 'Niobium',
    symbol: 'Nb',
    atomicNumber: 41,
    atomicMass: 92.906,
    category: 'Transition Metal',
    period: 5,
    group: 5,
  },
  {
    image: '/',
    name: 'Molybdenum',
    symbol: 'Mo',
    atomicNumber: 42,
    atomicMass: 95.95,
    category: 'Transition Metal',
    period: 5,
    group: 6,
  },
  {
    image: '/',
    name: 'Technetium',
    symbol: 'Tc',
    atomicNumber: 43,
    atomicMass: 98,
    category: 'Transition Metal',
    period: 5,
    group: 7,
  },
  {
    image: '/',
    name: 'Ruthenium',
    symbol: 'Ru',
    atomicNumber: 44,
    atomicMass: 101.07,
    category: 'Transition Metal',
    period: 5,
    group: 8,
  },
  {
    image: '/',
    name: 'Rhodium',
    symbol: 'Rh',
    atomicNumber: 45,
    atomicMass: 102.906,
    category: 'Transition Metal',
    period: 5,
    group: 9,
  },
  {
    image: '/',
    name: 'Palladium',
    symbol: 'Pd',
    atomicNumber: 46,
    atomicMass: 106.42,
    category: 'Transition Metal',
    period: 5,
    group: 10,
  },
  {
    image: '/',
    name: 'Silver',
    symbol: 'Ag',
    atomicNumber: 47,
    atomicMass: 107.868,
    category: 'Transition Metal',
    period: 5,
    group: 11,
  },
  {
    image: '/',
    name: 'Cadmium',
    symbol: 'Cd',
    atomicNumber: 48,
    atomicMass: 112.414,
    category: 'Transition Metal',
    period: 5,
    group: 12,
  },
  {
    image: '/',
    name: 'Indium',
    symbol: 'In',
    atomicNumber: 49,
    atomicMass: 114.818,
    category: 'Post-Transition Metal',
    period: 5,
    group: 13,
  },
  {
    image: '/',
    name: 'Tin',
    symbol: 'Sn',
    atomicNumber: 50,
    atomicMass: 118.71,
    category: 'Post-Transition Metal',
    period: 5,
    group: 14,
  },
  {
    image: '/',
    name: 'Antimony',
    symbol: 'Sb',
    atomicNumber: 51,
    atomicMass: 121.76,
    category: 'Metalloid',
    period: 5,
    group: 15,
  },
  {
    image: '/',
    name: 'Tellurium',
    symbol: 'Te',
    atomicNumber: 52,
    atomicMass: 127.6,
    category: 'Metalloid',
    period: 5,
    group: 16,
  },
  {
    image: '/',
    name: 'Iodine',
    symbol: 'I',
    atomicNumber: 53,
    atomicMass: 126.904,
    category: 'Halogen',
    period: 5,
    group: 17,
  },
  {
    image: '/',
    name: 'Xenon',
    symbol: 'Xe',
    atomicNumber: 54,
    atomicMass: 131.293,
    category: 'Noble Gas',
    period: 5,
    group: 18,
  },
  {
    image: '/',
    name: 'Cesium',
    symbol: 'Cs',
    atomicNumber: 55,
    atomicMass: 132.905,
    category: 'Alkali Metal',
    period: 6,
    group: 1,
  },
  {
    image: '/',
    name: 'Barium',
    symbol: 'Ba',
    atomicNumber: 56,
    atomicMass: 137.327,
    category: 'Alkaline Earth Metal',
    period: 6,
    group: 2,
  },
  {
    image: '/',
    name: 'Lanthanum',
    symbol: 'La',
    atomicNumber: 57,
    atomicMass: 138.905,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Cerium',
    symbol: 'Ce',
    atomicNumber: 58,
    atomicMass: 140.116,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Praseodymium',
    symbol: 'Pr',
    atomicNumber: 59,
    atomicMass: 140.908,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Neodymium',
    symbol: 'Nd',
    atomicNumber: 60,
    atomicMass: 144.242,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Promethium',
    symbol: 'Pm',
    atomicNumber: 61,
    atomicMass: 145,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Samarium',
    symbol: 'Sm',
    atomicNumber: 62,
    atomicMass: 150.36,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Europium',
    symbol: 'Eu',
    atomicNumber: 63,
    atomicMass: 151.964,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Gadolinium',
    symbol: 'Gd',
    atomicNumber: 64,
    atomicMass: 157.25,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Terbium',
    symbol: 'Tb',
    atomicNumber: 65,
    atomicMass: 158.925,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Dysprosium',
    symbol: 'Dy',
    atomicNumber: 66,
    atomicMass: 162.5,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Holmium',
    symbol: 'Ho',
    atomicNumber: 67,
    atomicMass: 164.93,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Erbium',
    symbol: 'Er',
    atomicNumber: 68,
    atomicMass: 167.259,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Thulium',
    symbol: 'Tm',
    atomicNumber: 69,
    atomicMass: 168.934,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Ytterbium',
    symbol: 'Yb',
    atomicNumber: 70,
    atomicMass: 173.045,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Lutetium',
    symbol: 'Lu',
    atomicNumber: 71,
    atomicMass: 174.967,
    category: 'Lanthanide',
    period: 6,
    group: 3,
  },
  {
    image: '/',
    name: 'Hafnium',
    symbol: 'Hf',
    atomicNumber: 72,
    atomicMass: 178.49,
    category: 'Transition Metal',
    period: 6,
    group: 4,
  },
  {
    image: '/',
    name: 'Tantalum',
    symbol: 'Ta',
    atomicNumber: 73,
    atomicMass: 180.948,
    category: 'Transition Metal',
    period: 6,
    group: 5,
  },
  {
    image: '/',
    name: 'Tungsten',
    symbol: 'W',
    atomicNumber: 74,
    atomicMass: 183.84,
    category: 'Transition Metal',
    period: 6,
    group: 6,
  },
  {
    image: '/',
    name: 'Rhenium',
    symbol: 'Re',
    atomicNumber: 75,
    atomicMass: 186.207,
    category: 'Transition Metal',
    period: 6,
    group: 7,
  },
  {
    image: '/',
    name: 'Osmium',
    symbol: 'Os',
    atomicNumber: 76,
    atomicMass: 190.23,
    category: 'Transition Metal',
    period: 6,
    group: 8,
  },
  {
    image: '/',
    name: 'Iridium',
    symbol: 'Ir',
    atomicNumber: 77,
    atomicMass: 192.217,
    category: 'Transition Metal',
    period: 6,
    group: 9,
  },
  {
    image: '/',
    name: 'Platinum',
    symbol: 'Pt',
    atomicNumber: 78,
    atomicMass: 195.084,
    category: 'Transition Metal',
    period: 6,
    group: 10,
  },
  {
    image: '/',
    name: 'Gold',
    symbol: 'Au',
    atomicNumber: 79,
    atomicMass: 196.967,
    category: 'Transition Metal',
    period: 6,
    group: 11,
  },
  {
    image: '/',
    name: 'Mercury',
    symbol: 'Hg',
    atomicNumber: 80,
    atomicMass: 200.592,
    category: 'Transition Metal',
    period: 6,
    group: 12,
  },
  {
    image: '/',
    name: 'Thallium',
    symbol: 'Tl',
    atomicNumber: 81,
    atomicMass: 204.38,
    category: 'Post-Transition Metal',
    period: 6,
    group: 13,
  },
  {
    image: '/',
    name: 'Lead',
    symbol: 'Pb',
    atomicNumber: 82,
    atomicMass: 207.2,
    category: 'Post-Transition Metal',
    period: 6,
    group: 14,
  },
  {
    image: '/',
    name: 'Bismuth',
    symbol: 'Bi',
    atomicNumber: 83,
    atomicMass: 208.98,
    category: 'Post-Transition Metal',
    period: 6,
    group: 15,
  },
  {
    image: '/',
    name: 'Polonium',
    symbol: 'Po',
    atomicNumber: 84,
    atomicMass: 209,
    category: 'Post-Transition Metal',
    period: 6,
    group: 16,
  },
  {
    image: '/',
    name: 'Astatine',
    symbol: 'At',
    atomicNumber: 85,
    atomicMass: 210,
    category: 'Halogen',
    period: 6,
    group: 17,
  },
  {
    image: '/',
    name: 'Radon',
    symbol: 'Rn',
    atomicNumber: 86,
    atomicMass: 222,
    category: 'Noble Gas',
    period: 6,
    group: 18,
  },
  {
    image: '/',
    name: 'Francium',
    symbol: 'Fr',
    atomicNumber: 87,
    atomicMass: 223,
    category: 'Alkali Metal',
    period: 7,
    group: 1,
  },
  {
    image: '/',
    name: 'Radium',
    symbol: 'Ra',
    atomicNumber: 88,
    atomicMass: 226,
    category: 'Alkaline Earth Metal',
    period: 7,
    group: 2,
  },
  {
    image: '/',
    name: 'Actinium',
    symbol: 'Ac',
    atomicNumber: 89,
    atomicMass: 227,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Thorium',
    symbol: 'Th',
    atomicNumber: 90,
    atomicMass: 232.038,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Protactinium',
    symbol: 'Pa',
    atomicNumber: 91,
    atomicMass: 231.036,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Uranium',
    symbol: 'U',
    atomicNumber: 92,
    atomicMass: 238.029,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Neptunium',
    symbol: 'Np',
    atomicNumber: 93,
    atomicMass: 237,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Plutonium',
    symbol: 'Pu',
    atomicNumber: 94,
    atomicMass: 244,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Americium',
    symbol: 'Am',
    atomicNumber: 95,
    atomicMass: 243,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Curium',
    symbol: 'Cm',
    atomicNumber: 96,
    atomicMass: 247,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Berkelium',
    symbol: 'Bk',
    atomicNumber: 97,
    atomicMass: 247,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Californium',
    symbol: 'Cf',
    atomicNumber: 98,
    atomicMass: 251,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Einsteinium',
    symbol: 'Es',
    atomicNumber: 99,
    atomicMass: 252,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Fermium',
    symbol: 'Fm',
    atomicNumber: 100,
    atomicMass: 257,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Mendelevium',
    symbol: 'Md',
    atomicNumber: 101,
    atomicMass: 258,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Nobelium',
    symbol: 'No',
    atomicNumber: 102,
    atomicMass: 259,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Lawrencium',
    symbol: 'Lr',
    atomicNumber: 103,
    atomicMass: 262,
    category: 'Actinide',
    period: 7,
    group: 3,
  },
  {
    image: '/',
    name: 'Rutherfordium',
    symbol: 'Rf',
    atomicNumber: 104,
    atomicMass: 267,
    category: 'Transition Metal',
    period: 7,
    group: 4,
  },
  {
    image: '/',
    name: 'Dubnium',
    symbol: 'Db',
    atomicNumber: 105,
    atomicMass: 270,
    category: 'Transition Metal',
    period: 7,
    group: 5,
  },
  {
    image: '/',
    name: 'Seaborgium',
    symbol: 'Sg',
    atomicNumber: 106,
    atomicMass: 271,
    category: 'Transition Metal',
    period: 7,
    group: 6,
  },
  {
    image: '/',
    name: 'Bohrium',
    symbol: 'Bh',
    atomicNumber: 107,
    atomicMass: 270,
    category: 'Transition Metal',
    period: 7,
    group: 7,
  },
  {
    image: '/',
    name: 'Hassium',
    symbol: 'Hs',
    atomicNumber: 108,
    atomicMass: 277,
    category: 'Transition Metal',
    period: 7,
    group: 8,
  },
  {
    image: '/',
    name: 'Meitnerium',
    symbol: 'Mt',
    atomicNumber: 109,
    atomicMass: 276,
    category: 'Unknown',
    period: 7,
    group: 9,
  },
  {
    image: '/',
    name: 'Darmstadtium',
    symbol: 'Ds',
    atomicNumber: 110,
    atomicMass: 281,
    category: 'Unknown',
    period: 7,
    group: 10,
  },
  {
    image: '/',
    name: 'Roentgenium',
    symbol: 'Rg',
    atomicNumber: 111,
    atomicMass: 280,
    category: 'Unknown',
    period: 7,
    group: 11,
  },
  {
    image: '/',
    name: 'Copernicium',
    symbol: 'Cn',
    atomicNumber: 112,
    atomicMass: 285,
    category: 'Transition Metal',
    period: 7,
    group: 12,
  },
  {
    image: '/',
    name: 'Nihonium',
    symbol: 'Nh',
    atomicNumber: 113,
    atomicMass: 284,
    category: 'Unknown',
    period: 7,
    group: 13,
  },
  {
    image: '/',
    name: 'Flerovium',
    symbol: 'Fl',
    atomicNumber: 114,
    atomicMass: 289,
    category: 'Unknown',
    period: 7,
    group: 14,
  },
  {
    image: '/',
    name: 'Moscovium',
    symbol: 'Mc',
    atomicNumber: 115,
    atomicMass: 288,
    category: 'Unknown',
    period: 7,
    group: 15,
  },
  {
    image: '/',
    name: 'Livermorium',
    symbol: 'Lv',
    atomicNumber: 116,
    atomicMass: 293,
    category: 'Unknown',
    period: 7,
    group: 16,
  },
  {
    image: '/',
    name: 'Tennessine',
    symbol: 'Ts',
    atomicNumber: 117,
    atomicMass: 294,
    category: 'Unknown',
    period: 7,
    group: 17,
  },
  {
    image: '/',
    name: 'Oganesson',
    symbol: 'Og',
    atomicNumber: 118,
    atomicMass: 294,
    category: 'Unknown',
    period: 7,
    group: 18,
  },
];

export function useElementData() {
  const [elements, setElements] = useState<Element[]>([]);

  useEffect(() => {
    setElements(elementData);
  }, []);

  return elements;
}
